### ISSUE TITLE
Click on info icon when on group page users list replace last login date to never

### ISSUE THREAD

**Issue by 1Jesper1** [passbolt/passbolt-appjs#10]
Passbolt Version: 2.4.0
Platform and Target:
-- Browser: Chrome

When click on the info icon when on group page users list, the last login date of the users are replaced with "Never".

**Comment by cedricalfonsi** [comment]
Thank you for your report @1Jesper1 
I am able to reproduce it, I added a ticket to our backlog (PASSBOLT-3245)

**Comment by cedricalfonsi** [comment]
Fixed with v2.11.0
