### ISSUE TITLE
Opening an URI in a new tab leads to /SAFE_URI

### ISSUE THREAD

**Issue by martinvonwittich** [passbolt/passbolt-appjs#16]
* Passbolt version: 2.11.0
* Passbolt extension version: 2.11.1
* Browser: Chrome Version 77.0.3865.90

I have a password entry that looks like this:

| Resource | Username | Password | URI | Modified |
|-|-|-|-|-|
| my.name@example.com | my.name@example.com | ●●●●●●●●● | https://example.com | 2 years ago |

When I click on the URI link with the middle mouse button, it'll open a new tab that points to https://my.passbolt.domain/SAFE_URI instead of https://example.com. As far as I remember, this worked fine before the last update.

This only affects the list view, not the detail view on the right that you get when you click anywhere on a password line. It's pretty annoying because it breaks the workflow that I've been using till now: 1) click on the password to copy it 2) middle-click on the URI 3) use the browser autocompletion to fill the user name 4) paste the password and login.

**Comment by stripthis** [comment]
Hello @martinvonwittich,

I can reproduce the issue here, we'll get it fixed in the next release. 
Sorry for the inconvenience.

**Comment by cedricalfonsi** [comment]
It has been fixed with a previous release.
