### ISSUE TITLE
Allow configuration of password generator

### ISSUE THREAD

**Issue by Dehalion** [passbolt/passbolt-appjs#18]
The current password generator used for creating new passwords always generates passwords containing many special characters.

Sometimes it is not possible to use those passwords because of restrictions which cannot be changed.

It would be great if the password generator could be configured, at server or user level, to generate only long passwords containing `[0-9a-zA-Z]`.

**Comment by cedricalfonsi** [comment]
Hello @Dehalion,

Sorry for the delay.

I'm closing this ticket as it is relative to a feature request, and we centralize them on our community forum. 

The feature you are mentioning is described [there](https://community.passbolt.com/t/as-a-user-generating-a-password-automatically-i-should-be-able-to-change-the-default-length-and-character-scheme/63). Don't hesitate to comment it or vote for it.
