### ISSUE TITLE
Feature request: Link to specific password

### ISSUE THREAD

**Issue by Trandel** [passbolt/passbolt-appjs#3]
Hello Passbolt team,

It would be very helpful to be able to create a link for a specific password. We are managing a lot of passwords and sometimes users can't find the right one. All our documentation is on confluence and links for a specific password in passbolt would be great. 

The other option might be a way to populate search box from URI like:
`http://domain.tld/?s=thisIsTheOneYouNeed`

What do you think guys?

**Comment by grahl** [comment]
Would also really appreciate the button, thanks for the link to generate them manually for now.

**Comment by cedricalfonsi** [comment]
Hello @grahl,
This feature has been release along with v2.7.0
