### ISSUE TITLE
Upper logout link doesn't work when mounted in subdirectory

### ISSUE THREAD

**Issue by udl** [passbolt/passbolt-appjs#5]
Hi there,

first of all thank you for the great product.
I discovered a little bug:

My passbolt instance is running with docker behind a traefik reverse proxy and is reachable as `https://my.toplevel.domain/passbolt`, configured via the environment variable `APP_FULL_BASE_URL=https://my.toplevel.domain/passbolt`.
Everything's working fine except for the upper right logout link. That one's pointing to `https://my.toplevel.domain/auth/logout`. So there's a passbolt missing in the path.
However I can logout when I click the link that's in the profile dropdown menu.

**Comment by cedricalfonsi** [comment]
Hello @udl,
Thank you for your report.
This bug is known to us and it will be fixed with the next release v2.2.0.

**Comment by cedricalfonsi** [comment]
And thank you for your kind words it is appreciated

**Comment by cedricalfonsi** [comment]
Fixed with v2.2.0
