### ISSUE TITLE
Group filter link stays active after switching to a non group filter

### ISSUE THREAD

**Issue by joberthel** [passbolt/passbolt-appjs#6]
1. I clicked at a group in the "Filter by group" section.
2. Now I clicked at one of the filters at the top (All items, Favorite, Recently modified, ...)
3. The link to the group filter is still active and I can't filter by the same group again. I first have to click at another group.

Version: 2.2.0/2.2.0
Docker: 2.2.0-debian

![bildschirmfoto 2018-08-14 um 09 16 13](https://user-images.githubusercontent.com/34104366/44077081-bd5d1dd2-9fa2-11e8-80be-cf8544103ab6.png)

**Comment by cedricalfonsi** [comment]
Hello @joberthel,
Thank you for the report, I added the issue in the current sprint (ref PASSBOLT-2965).
A fix will be published with the next release.
Best regards

**Comment by cedricalfonsi** [comment]
Fixed with v2.3.0
