### ISSUE TITLE
User recovery doesn't work when mounted in subdirectory

### ISSUE THREAD

**Issue by udl** [passbolt/passbolt-appjs#7]
Hi there,

just tried to switch computers and therefore recover my user.
Our passbolt is mounted under https://example.com/passbolt.
Clicking on the recovery button after filling in my email address sends me to https://example.com/users/recover - leaving out the passbolt.

I guess, that's a bug?

**Comment by cedricalfonsi** [comment]
Hello @udl,

Unfortunately when passbolt is installed in a subdirectory you may encounter some issues, mainly related to the emails and the urls they can contain.
I'm closing this ticket as it is already referenced on the API repository, see: https://github.com/passbolt/passbolt_api/issues/252
